name: Mi primer CI

on:
  push:
    branches: [master]

jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
      - name: Paso que funciona
        run: echo "Este paso s√≠ funciona"

      - name: Paso que falla
        run: exit 1
